{% raw %}
{% set data = load_setup_py_data() %}
{% endraw %}

package:
  name: {{ cookiecutter.import_name }}
{%- raw %}
  version: {{ data.get('version') }}
{%- endraw %}

source:
  path: ..

build:
  number: 0
  noarch: python

requirements:
  build:
    - python >=3.7
    - setuptools
  run:
    - python >=3.7

test:
  imports:
    - {{ cookiecutter.import_name }}
  requires:
    - pytest

about:
  home: https://github.com/{{ cookiecutter.github_repo_group }}/{{ cookiecutter.repo_name }}
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  summary: {{ cookiecutter.description }}
