name: Cookiecutter Test

on:
  push:
  pull_request:

jobs:
  pip-test:
    name: "Python 3.9: pip"
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
